#!/bin/bash

source ${CONTAINER_SCRIPTS_PATH}/common.sh
set -eu

# setup directory for data
chown -R valkey:0 "${HOME}" "${VALKEY_CONF}"
restorecon -R "${HOME}" "${VALKEY_CONF}"

# Loosen permission bits for group to avoid problems running container with
# arbitrary UID
# When only specifying user, group is 0, that's why /var/lib/valkey must have
# owner valkey.0; that allows to avoid a+rwx for this dir
chmod 0770 "${HOME}" "${VALKEY_DATADIR}"
chmod 0660 "${VALKEY_CONF}"

# adjust config with changes we do every-time
clear_config
envsubst < ${CONTAINER_SCRIPTS_PATH}/base.conf.template >> "${VALKEY_CONF}"
